FROM alpine
MAINTAINER clark <5200374@qq.com>
LABEL Description="Easy to use SSH Tunnel based in the Alpine Linux docker imageon Raspberry Pi"

RUN apk --update add openssh-client \
    && rm -f /var/cache/apk/*

# Security fix for CVE-2016-0777 and CVE-2016-0778
RUN echo -e 'Host *\nUseRoaming no' >> /etc/ssh/ssh_config \
RUN mkdir ~/.ssh
ADD run.sh /root/
RUN chmod a+x /root/run.sh
ENTRYPOINT ["/root/run.sh"]
